{"success": false, "error": "Traceback (most recent call last):\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py\", line 813, in parse_args_and_execute\n    enable_online_lookup=query_signature,\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/mythril/mythril_disassembler.py\", line 38, in __init__\n    self.solc_binary = self._init_solc_binary(solc_version)\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/mythril/mythril_disassembler.py\", line 75, in _init_solc_binary\n    solc.install_solc(\"v\" + version)\n  File \"/home/tiago/.local/lib/python3.6/site-packages/solc/install.py\", line 513, in install_solc\n    install_fn()\n  File \"/home/tiago/.local/lib/python3.6/site-packages/solc/install.py\", line 334, in install_solc_from_static_linux\n    download_static_release(identifier)\n  File \"/home/tiago/.local/lib/python3.6/site-packages/solc/install.py\", line 277, in download_static_release\n    message=\"Downloading static linux binary from {0}\".format(download_uri),\n  File \"/home/tiago/.local/lib/python3.6/site-packages/solc/install.py\", line 106, in check_subprocess_call\n    **proc_kwargs\n  File \"/usr/lib/python3.6/subprocess.py\", line 311, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command '['wget', 'https://github.com/ethereum/solidity/releases/download/v0.4.19/solc-static-linux', '-c', '-O', '/home/tiago/.py-solc/solc-v0.4.19/bin/solc']' returned non-zero exit status 4.\n", "issues": []}
